on:  
  schedule:
  - cron:  0 2 * * *
name: Update and build PrusaSlicer
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: login
      uses: actions/docker/login@c08a5fc9e0286844156fefff2c141072048141f6
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: check latest prusaslicer release
      uses: actions/bin/sh@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: '"apt-get update" "apt-get -y install curl jq git" ./tagLatestPrusaSlicer.sh'
    - name: buildpush prusaslicer
      uses: davidk/docker/cli-multi@cli-loop
      with:
        args: '"build -t keyglitch/docker-slic3r-prusa3d:latest -f /github/workspace/Dockerfile
          ." "tag keyglitch/docker-slic3r-prusa3d:latest keyglitch/docker-slic3r-prusa3d:$(cat
          /github/workspace/VERSION)" "tag keyglitch/docker-slic3r-prusa3d:latest
          keyglitch/prusaslicer:latest" "tag keyglitch/prusaslicer:latest keyglitch/prusaslicer:$(cat
          /github/workspace/VERSION)" "push keyglitch/docker-slic3r-prusa3d" "push
          keyglitch/prusaslicer"'
